package framework.mybatis.dao;

import framework.mybatis.entity.Tbl_LrFreeCustomerInfo;

public interface Tbl_LrFreeCustomerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_LRFREECUSTOMERINFO
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    int insert(Tbl_LrFreeCustomerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_LRFREECUSTOMERINFO
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    int insertSelective(Tbl_LrFreeCustomerInfo record);
}