package framework.mybatis.entity;

import java.util.Date;

public class Tbl_LrFreeCustomerInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.CUSTOMERID
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String customerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.NAME
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.GENDER
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.BIRTHDAY
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.IDTYPE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String idtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.IDNO
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String idno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.DIPLOMA
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String diploma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.DEGREE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.ISMERRIED
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String ismerried;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.ILLNESS
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String illness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.COMPANY
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.EMAIL
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.PROVINCE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.CITY
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.DISTRICT
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.COUNTY
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.ZIPCODE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String zipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.MOBILEPHONE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String mobilephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.SECONDPHONE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String secondphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.STREET
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.CAREERCODE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String careercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.CAREERTYPE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String careertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.NOTES
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.USERID
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.OPERATORID
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String operatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.MODIFIEDTIME
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private Date modifiedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.MAKETIME
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private Date maketime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.ENABLED
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.SOURCECHANNEL
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String sourcechannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.INPUTNUM
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String inputnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.REWRITE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String rewrite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.REWRITE0
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String rewrite0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.REWRITE1
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String rewrite1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.REWRITE2
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String rewrite2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_LRFREECUSTOMERINFO.REWRITE3
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    private String rewrite3;

    public Tbl_LrFreeCustomerInfo(String customerid2, String name2, String gender2, Date birthday2) {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.CUSTOMERID
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.CUSTOMERID
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.CUSTOMERID
     *
     * @param customerid the value for TBL_LRFREECUSTOMERINFO.CUSTOMERID
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.NAME
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.NAME
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.NAME
     *
     * @param name the value for TBL_LRFREECUSTOMERINFO.NAME
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.GENDER
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.GENDER
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.GENDER
     *
     * @param gender the value for TBL_LRFREECUSTOMERINFO.GENDER
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.BIRTHDAY
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.BIRTHDAY
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.BIRTHDAY
     *
     * @param birthday the value for TBL_LRFREECUSTOMERINFO.BIRTHDAY
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.IDTYPE
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.IDTYPE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getIdtype() {
        return idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.IDTYPE
     *
     * @param idtype the value for TBL_LRFREECUSTOMERINFO.IDTYPE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setIdtype(String idtype) {
        this.idtype = idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.IDNO
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.IDNO
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.IDNO
     *
     * @param idno the value for TBL_LRFREECUSTOMERINFO.IDNO
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setIdno(String idno) {
        this.idno = idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.DIPLOMA
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.DIPLOMA
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getDiploma() {
        return diploma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.DIPLOMA
     *
     * @param diploma the value for TBL_LRFREECUSTOMERINFO.DIPLOMA
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setDiploma(String diploma) {
        this.diploma = diploma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.DEGREE
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.DEGREE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.DEGREE
     *
     * @param degree the value for TBL_LRFREECUSTOMERINFO.DEGREE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setDegree(String degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.ISMERRIED
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.ISMERRIED
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getIsmerried() {
        return ismerried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.ISMERRIED
     *
     * @param ismerried the value for TBL_LRFREECUSTOMERINFO.ISMERRIED
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setIsmerried(String ismerried) {
        this.ismerried = ismerried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.ILLNESS
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.ILLNESS
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getIllness() {
        return illness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.ILLNESS
     *
     * @param illness the value for TBL_LRFREECUSTOMERINFO.ILLNESS
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setIllness(String illness) {
        this.illness = illness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.COMPANY
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.COMPANY
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.COMPANY
     *
     * @param company the value for TBL_LRFREECUSTOMERINFO.COMPANY
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.EMAIL
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.EMAIL
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.EMAIL
     *
     * @param email the value for TBL_LRFREECUSTOMERINFO.EMAIL
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.PROVINCE
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.PROVINCE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.PROVINCE
     *
     * @param province the value for TBL_LRFREECUSTOMERINFO.PROVINCE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.CITY
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.CITY
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.CITY
     *
     * @param city the value for TBL_LRFREECUSTOMERINFO.CITY
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.DISTRICT
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.DISTRICT
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.DISTRICT
     *
     * @param district the value for TBL_LRFREECUSTOMERINFO.DISTRICT
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.COUNTY
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.COUNTY
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.COUNTY
     *
     * @param county the value for TBL_LRFREECUSTOMERINFO.COUNTY
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.ZIPCODE
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.ZIPCODE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.ZIPCODE
     *
     * @param zipcode the value for TBL_LRFREECUSTOMERINFO.ZIPCODE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.MOBILEPHONE
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.MOBILEPHONE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.MOBILEPHONE
     *
     * @param mobilephone the value for TBL_LRFREECUSTOMERINFO.MOBILEPHONE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.SECONDPHONE
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.SECONDPHONE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getSecondphone() {
        return secondphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.SECONDPHONE
     *
     * @param secondphone the value for TBL_LRFREECUSTOMERINFO.SECONDPHONE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setSecondphone(String secondphone) {
        this.secondphone = secondphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.STREET
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.STREET
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.STREET
     *
     * @param street the value for TBL_LRFREECUSTOMERINFO.STREET
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.CAREERCODE
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.CAREERCODE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getCareercode() {
        return careercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.CAREERCODE
     *
     * @param careercode the value for TBL_LRFREECUSTOMERINFO.CAREERCODE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setCareercode(String careercode) {
        this.careercode = careercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.CAREERTYPE
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.CAREERTYPE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getCareertype() {
        return careertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.CAREERTYPE
     *
     * @param careertype the value for TBL_LRFREECUSTOMERINFO.CAREERTYPE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setCareertype(String careertype) {
        this.careertype = careertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.NOTES
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.NOTES
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.NOTES
     *
     * @param notes the value for TBL_LRFREECUSTOMERINFO.NOTES
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.USERID
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.USERID
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.USERID
     *
     * @param userid the value for TBL_LRFREECUSTOMERINFO.USERID
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.OPERATORID
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.OPERATORID
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.OPERATORID
     *
     * @param operatorid the value for TBL_LRFREECUSTOMERINFO.OPERATORID
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setOperatorid(String operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.MODIFIEDTIME
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.MODIFIEDTIME
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public Date getModifiedtime() {
        return modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.MODIFIEDTIME
     *
     * @param modifiedtime the value for TBL_LRFREECUSTOMERINFO.MODIFIEDTIME
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setModifiedtime(Date modifiedtime) {
        this.modifiedtime = modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.MAKETIME
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.MAKETIME
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public Date getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.MAKETIME
     *
     * @param maketime the value for TBL_LRFREECUSTOMERINFO.MAKETIME
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.ENABLED
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.ENABLED
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.ENABLED
     *
     * @param enabled the value for TBL_LRFREECUSTOMERINFO.ENABLED
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.SOURCECHANNEL
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.SOURCECHANNEL
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getSourcechannel() {
        return sourcechannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.SOURCECHANNEL
     *
     * @param sourcechannel the value for TBL_LRFREECUSTOMERINFO.SOURCECHANNEL
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setSourcechannel(String sourcechannel) {
        this.sourcechannel = sourcechannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.INPUTNUM
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.INPUTNUM
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getInputnum() {
        return inputnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.INPUTNUM
     *
     * @param inputnum the value for TBL_LRFREECUSTOMERINFO.INPUTNUM
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setInputnum(String inputnum) {
        this.inputnum = inputnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.REWRITE
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.REWRITE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getRewrite() {
        return rewrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.REWRITE
     *
     * @param rewrite the value for TBL_LRFREECUSTOMERINFO.REWRITE
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setRewrite(String rewrite) {
        this.rewrite = rewrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.REWRITE0
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.REWRITE0
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getRewrite0() {
        return rewrite0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.REWRITE0
     *
     * @param rewrite0 the value for TBL_LRFREECUSTOMERINFO.REWRITE0
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setRewrite0(String rewrite0) {
        this.rewrite0 = rewrite0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.REWRITE1
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.REWRITE1
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getRewrite1() {
        return rewrite1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.REWRITE1
     *
     * @param rewrite1 the value for TBL_LRFREECUSTOMERINFO.REWRITE1
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setRewrite1(String rewrite1) {
        this.rewrite1 = rewrite1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.REWRITE2
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.REWRITE2
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getRewrite2() {
        return rewrite2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.REWRITE2
     *
     * @param rewrite2 the value for TBL_LRFREECUSTOMERINFO.REWRITE2
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setRewrite2(String rewrite2) {
        this.rewrite2 = rewrite2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_LRFREECUSTOMERINFO.REWRITE3
     *
     * @return the value of TBL_LRFREECUSTOMERINFO.REWRITE3
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public String getRewrite3() {
        return rewrite3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_LRFREECUSTOMERINFO.REWRITE3
     *
     * @param rewrite3 the value for TBL_LRFREECUSTOMERINFO.REWRITE3
     *
     * @mbggenerated Fri Jul 22 16:50:42 CST 2016
     */
    public void setRewrite3(String rewrite3) {
        this.rewrite3 = rewrite3;
    }
}